"""
This is the most important file in the whole project simply because it contains the core logic for analyzing images and determining if they are AI-generated or not.
There are three main steps/signals to this process:

Signal 1: FFT Artifact score
FFT stands for Fast Fourier Transform, which converts the image from pixel values into frequency data. Real camera photos have a natural, somewhat random frequency distribution.
AI generated images have a repeating pattern in the frequency domain and a kind of "grid" like artifact because of how disffusion models and GANs(Generative Adversarial Networks) generate pixels. This is one of 
the most reliable signals for detecting AI generated images.

Signal 2: Noise Pattern Score
Every real camera sennsor has a unique noise fingerprint calle PRNU (Photo Response Non-Uniformity). Even on a clean photo there's microscopic random noise from the senson. AI generated
images hhas no sensor(s) so they either have no noise, or artificially mooth areas that look unnaturally clean. We measure how "natural" the noise distribution looks.

Signal 3: Metada Score
Real photos taken on a camera or a phone contains EXIF metadata which contains camera model, lens, gps, timestamp, software, etc. AI generated images often have none of this, or have suspicious
metadata (generated by Stable Diffusion, DALL-E, etc). Absence of expected metadata is a weak but useful signal.

Signal 4: LBP Texture Score
Local Binary Patterns (LBP) captiures micro-texture across all color channels at muiltuple scales. Real photos have characteristic texture histograms shaped by physics - lens blur, sensor noise, depth of filed.
AI images produce flatter, more uniformed histograms.

Signal 5: ONNX Classifier Score
A fine-tuned SwinV2 vision transformer trained speficially to distinguis AI generated vs real images. Runs entirely locally via ONNX runtime - no external API calls.

Signal 6: Anatomical Score (face images only)
If a face is detected, runs a full 68-point facial landmark check looking for geometric inconsistencies - eye asymmetry, nos misalignment, unnatural jaw lines - that AI still struggles to get right.
"""

import asyncio
import glob
import io
import json
import logging
import math
from typing import Any, Optional

import cv2
import dlib
import numpy as np
import onnxruntime as ort
from PIL import Image, ImageFilter
from skimage.feature import local_binary_pattern

from app.core.config import get_settings
from app.features.image.schemas import (
    ConfidenceLevel,
    ImageDetectionResult,
    ImageSignals,
)

logger = logging.getLogger(__name__)
settings = get_settings()

class ImageDetectionService:
    """ Weights for combining signals into final score
    Must sum to 1.0
    """
    _WEIGHTS = {
        "fft":        0.05,   # modern AI defeats this
        "noise":      0.05,   # too easily confused by complex scenes
        "metadata":   0.10,   # useful but weak
        "lbp":        0.10,   # complex scenes fool it
        "classifier": 0.60,   # most reliable by far
        "anatomical": 0.10,   # useful when face present
    }

    def __init__(self) -> None:
        self._ort_session = None
        self._classifier_labels = None
        self._face_detector = None
        self._landmark_predictor = None
        self._models_loaded = False
    
    def load_models(self) -> None:
        """
        Load all model weights into memory.
        Called once at startup from main.py lifespan - not on every request.
        """
        logger.info("Loading image detection models...")

        # --- ONNX Classifier ---
        models_files = glob.glob(
            f"{settings.efficientnet_model_dir}/**/model.onnx",
            recursive=True
        )
        if not models_files:
            raise RuntimeError(
                f"No model.onnx found under {settings.efficientnet_model_dir}."
                "Run the model download script first."
            )
        
        self._ort_session = ort.InferenceSession(models_files[0])
        logger.info("ONNX classifier loaded from %s", models_files[0])

        # Load label mapping from config.json sitting next to the model.
        config_files = glob.glob(
            f"{settings.efficientnet_model_dir}/**/config.json",
            recursive=True
        )
        if config_files:
            with open(config_files[0]) as f:
                config = json.load(f)
            self._classifier_labels = config.get("id2label", {"0": "artificial", "1": "real"})
        else:
            # Fallback based on what we confirmed from the repo.
            self._classifier_labels = {"0": "artificial", "1": "real"}
        
        logger.info("Classifier labels: %s", self._classifier_labels)

        # --- Dlib face detector + 68-point landmark predictor ---
        self._face_detector = dlib.get_frontal_face_detector()
        self._landmark_predictor = dlib.shape_predictor(settings.dlib_landmark_model)
        logger.info("Dlib face detector and landmark predictor loaded.")

        self._models_loaded = True
        logger.info("All image detection models loaded successfully.")
    

    # ---------------------------------------------------------------------------------------
    # Entry Point
    # ---------------------------------------------------------------------------------------

    async def analyze(self, contents: bytes) -> ImageDetectionResult:
        """
        Entry point. Runs all signals concurrently then combines them.
        """

        image = self._load_image(contents)
        exif = self._extract_exif(contents)

        # CPU-bound signals run in the thread pool so event loop stays unblocked.
        loop = asyncio.get_event_loop()
        fft_score, noise_score, lbp_score, classifier_score = await asyncio.gather(
            loop.run_in_executor(None, self._fft_artifact_score, image),
            loop.run_in_executor(None, self._noise_pattern_score, image),
            loop.run_in_executor(None, self._lbp_texture_score, image),
            loop.run_in_executor(None, self._classifier_score, image),
        )

        metadata_score = self._metadata_score(exif)

        # Anatomical check - only runs if a face is present.
        face_detected, anatomical_score = await loop.run_in_executor(
            None, self._anatomical_score, image
        )

        signals = ImageSignals(
            fft_artifact_score=round(fft_score, 4),
            noise_pattern_score=round(noise_score, 4),
            metadata_score=round(metadata_score, 4),
            lbp_texture_score=round(lbp_score, 4),
            classifier_score=round(classifier_score, 4),
            anatomical_score=round(anatomical_score, 4) if face_detected else None,
        )

        ai_probability = self._combine(signals, face_detected)
        confidence = self._confidence(signals, face_detected)
        verdict = self._verdict(ai_probability)

        logger.info(
            "image_analysis_complete fft=%.3f noise=%.3f  meta=%.3f  "
            "lbp=%3f classifier=%.3f anatomical=%s final=%.3f",
            fft_score, noise_score, metadata_score,
            lbp_score, classifier_score,
            f"{anatomical_score:.3f}" if face_detected else "n/a",
            ai_probability,
        )

        return ImageDetectionResult(
            ai_probability=round(ai_probability, 4),
            confidence=confidence,
            signals=signals,
            verdict=verdict,
            face_detected=face_detected,
        )

    # --------------------------------------------------------------------------------------
    # Signal 1: FFT Artifact Detection
    # --------------------------------------------------------------------------------------
    def _fft_artifact_score(self, image: Image.Image) -> float:
        """
        Converts the image to frequency domain and looks for the grid-like repeating patternts
        that diffusion models and GANs leave behind.
        """

        # Work in grayscale - color channels add noise to frequency analysis
        gray = np.array(image.convert("L"), dtype=np.float32) # Convert to grayscale and float32 for processing.
        fft = np.fft.fft2(gray)         # 2D FFT to get frequency data.
        shift = np.fft.fftshift(fft)    # Center the zero frequency.
        mag = np.log1p(np.abs(shift))   # Log scale to readability.

        h, w = mag.shape
        cy, cx = h // 2, w // 2

        # Compare energy in the center (low frequency, natural content)
        # Vs energy at the edges (high frequency, where AI artifacts appear)
        center_region = mag[cy-10:cy+10, cx-10:cx+10]
        edge_region = np.concatenate([
            mag[:10, :].ravel(),
            mag[-10:, :].ravel(),
            mag[:, :10].ravel(),
            mag[:, -10:].ravel(),
        ])

        center_energy = float(np.mean(center_region))
        edge_energy = float(np.mean(edge_region))

        if center_energy == 0:
            return 0.5
        
        # AI imges have disproportionately high edge energy relative to center.
        ratio = edge_energy / center_energy
        score = self._sigmoid(ratio - 0.5)
        return float(np.clip(score, 0.0, 1.0))

    # --------------------------------------------------------------------------------------
    # Signal 2: Noise Pattern Analysis
    # --------------------------------------------------------------------------------------
    def _noise_pattern_score(self, image: Image.Image) -> float:
        """
        Extracts the noise layer and checks wheather it looks like natural sensor noise (random)
        or AI smooth/artificial noise.

        Returns a score 0.0-1.0 where 1.0 = strong AI signal.
        """

        gray = np.array(image.convert("L"), dtype=np.float32)

        # Extract noise by subtracting a blurred version of the image from the original.
        blurred = np.array(
            image.convert("L").filter(ImageFilter.GaussianBlur(radius=2)),
            dtype=np.float32,
        )
        noise = gray - blurred
        std = float(np.std(noise))
        mean = float(np.abs(np.mean(noise)))

        # Real camera noise: high std (lots of variation), mean near zero
        # AI noise: unnaturally low std (too smooth) or high mean (bias)
        if std < 1.0:
            # Almost no noise - suspiciously clean
            return 0.85
        
        # Coefficient of variation - lower means more artificially uniform noise
        cv = mean / std if std > 0 else 0
        score = self._sigmoid(cv * 2 - 1)
        return float(np.clip(score, 0.0, 1.0))
    
    # --------------------------------------------------------------------------------------
    # Signal 3: Metadata Analysis
    # --------------------------------------------------------------------------------------
    def _metadata_score(self, exif: dict[str, Any]) -> float:
        """
        Checks EXIF metadata for signs of AI generation. Real photos have rich metadata. AI
        images typically have none, or metadata that explicitly names an AI tool.

        Returns a score 0.0-1.0 where 1.0 = strong AI signal.
        """

        AI_TOOLS = {
            "stable diffusion", "midjourney", "dall-e",
            "firefly", "imagen", "runway", "leonardo",
        }

        if not exif:
            # No metadata at all - moderately suspicious.
            return 0.65
        
        # Check all string values for AI tool names.
        all_values = " ".join(str(v).lower() for v in exif.values())
        if any(tool in all_values for tool in AI_TOOLS):
            return 0.99
        
        # Count how many expected camera fields are present. Fewer fields = more suspicious.
        camera_fields = {"Make", "Model", "LensModel", "DateTime", "GPSInfo"}
        present = sum(1 for f in camera_fields if f in exif)
        completeness = present / len(camera_fields)
        
        # Fewer camera fields = more likely AI.
        return round(1.0 - (completeness * 0.6), 4)
    
    # --------------------------------------------------------------------------------------
    # Signal 4 - LBP multi-scale texture analysis
    # --------------------------------------------------------------------------------------
    def _lbp_texture_score(self, image: Image.Image) -> float:
        """
        Runs LBP at three scales across all three color channels. AI images produce flatter,
        more uniform histogram because they lack the micro-texture variation that physical image
        produces. Returns a score 0.0-1.0 where 1.0 = string AI signal.
        """
        image_rgb = np.array(image.convert("RGB"))
        scores = []

        # Three scales - captures texture at different granularities.
        scales = [
            (1, 8),   # Fine texture
            (2, 16),  # Medium texture
            (3, 24),  # Coarse texture
        ]

        for channel in range(3):
            channel_data = image_rgb[:, :, channel] # Extract one color channel at a time - noise and texture can vary between channels.
            for radius, n_points in scales:
                lbp = local_binary_pattern(channel_data, n_points, radius, method="uniform")    # Compute LBP for this channel and scale.
                hist, _ = np.histogram(lbp.ravel(), bins=n_points + 2, range=(0, n_points + 2)) # Uniform LBP produces n_points + 2 possible patterns.
                hist = hist.astype(float)  # Convert to float for processing.
                hist /= hist.sum() + 1e-6  # Normalize to get a probability distribution.

                # Uniformity - AI images have more uniform histograms, so we measure how close the histogram is to a uniform distribution.
                uniformity = float(np.sum(hist ** 2))   # Closer to 1.0 means more uniform, which is more suspicious.
                n_bins = n_points + 2 # Total number of possible patterns for uniform LBP.
                uniform_baseline = 1.0 / n_bins
                deviation = abs(uniformity - uniform_baseline) # Deviation from uniform distribution.

                # Low deviation = close to uniform = more likely AI.
                score = 1.0 - min(deviation * n_bins * 2, 1.0) # Scale deviation to 0-1 range where 1.0 is very close to uniform.
                scores.append(score)
        
        return float(np.clip(np.mean(scores), 0.0, 1.0))
    
    # --------------------------------------------------------------------------------------
    # Signal 5 - ONNX Classifier
    # --------------------------------------------------------------------------------------
    def _classifier_score(self, image: Image.Image) -> float:
        """
        Runs the image through a fine-tuned SwinV2 vision transformer exported to ONNX format.
        Trained speficically to distinguish AI generated from real photographs. Runs entirely locally -
        no external API calls. Returns a score 0.0-1.0 where 1.0 = strong AI signal.
        """
        if not self._models_loaded or self._ort_session is None:
            logger.warning("ONNX model not loaded - classifier score will be 0.5 (neutral)")
            return 0.5
        
        # Preprocess the image to 224x224, normalize to ImageNet stats.
        img = image.convert("RGB").resize((256, 256))   # Resize to model input size.
        arr = np.array(img, dtype=np.float32) / 255.0   # Normalize to 0-1 range.

        mean = np.array([0.485, 0.456, 0.406], dtype=np.float32) # Normalize to ImageNet mean and std - common practice for vision models.
        std = np.array([0.229, 0.224, 0.225], dtype=np.float32) # ImageNet std
        arr = (arr - mean) / std # Standardize each channel.

        # Convert HWC -> CHW ->NCHW (batch of 1)
        arr = arr.transpose(2, 0, 1)[np.newaxis, :] # Model expects input shape (1, 3, 224, 224).

        outputs = self._ort_session.run(
            ["logits"],
            {"pixel_values": arr}
        ) # Get raw logits from the model - these are unnormalized scores for each class (real vs AI).
        logits = outputs[0][0] # Shape (2,) - one logit for each class.

        # Softmax to get probabilities. We take the probability of the "AI" class as the score.
        exp_logits = np.exp(logits - np.max(logits)) # Subtract max for numerical stability.
        probs = exp_logits / exp_logits.sum() # Normalize to get probabilities.

        # Index 0 = "artificial" (confirmed from config.json)
        ai_score = float(probs[0])
        return float(np.clip(ai_score, 0.0, 1.0))
    
    # --------------------------------------------------------------------------------------
    # Signal 6 - Anatomical landmark geometry check
    # --------------------------------------------------------------------------------------
    def _anatomical_score(self, image: Image.Image) -> float:
        """
        Detects faces and runs a full 68-poiont landmark check.
        Returns (face_detected, score) where score is 0.0-1.0 with 1.0 = strong AI signal.

        Checks:
        - Eye symmetry (height difference)
        - Nose alignment relative to face center
        - Mouth symmetry
        - Eye-to-mouth proportion ratio
        - Jaw line distance variance
        """
        if not self._models_loaded:
            return False, 0.5
        
        img_gray = cv2.cvtColor(np.array(image.convert("RGB")), cv2.COLOR_RGB2GRAY)
        faces = self._face_detector(img_gray, 1)

        if not faces:
            return False, 0.5
        
        # Analyze the largest detected face.
        face = max(faces, key=lambda r: r.width() * r.height())
        landmarks = self._landmark_predictor(img_gray, face)
        points = np.array([[landmarks.part(i).x, landmarks.part(i).y]
                            for i in range(68)])
        
        anomaly_scores = []

        # --- Eye symmetry ---
        left_eye = points[36:42]  # Left eye landmarks
        right_eye = points[42:48] # Right eye landmarks
        left_center = left_eye.mean(axis=0)
        right_center = right_eye.mean(axis=0)

        eye_height_diff = abs(left_center[1] - right_center[1])
        eye_symmetry = eye_height_diff / face.height() # Normalize by face height
        anomaly_scores.append(self._sigmoid(eye_symmetry * 30 - 2)) # Scale to 0-1 range where higher means more asymmetry = more suspicious.

        # --- Nose alignment ---
        nose_tip = points[30] # Nose tip landmark.
        face_center_x = (face.left() + face.right()) / 2
        nose_offset = abs(nose_tip[0] - face_center_x) / face.width() # Normalize by face width.
        anomaly_scores.append(self._sigmoid(nose_offset * 20 - 1)) # Higher offset = more suspicious.

        # --- Mouth symmetry ---
        mouth_left = points[48]  # Left corner of mouth
        mouth_right = points[54] # Right corner of mouth
        mouth_height_diff = abs(mouth_left[1] - mouth_right[1])
        mouth_symmetry = mouth_height_diff / face.height() # Normalize by face height.
        anomaly_scores.append(self._sigmoid(mouth_symmetry * 25 - 2))

        # -- Eye-to-mouth proportion ratio ---
        eye_mid_y = (left_center[1] + right_center[1]) / 2
        mouth_mid_y = (mouth_left[1] + mouth_right[1]) / 2
        eye_mouth_dist = abs(mouth_mid_y - eye_mid_y)
        proportion = eye_mouth_dist / face.height() # Normalize by face height.
        # Real human faces: this ratio is typically 0.28-0.38. AI generated faces can have more extreme ratios.
        proportion_anomaly = abs(proportion - 0.33) / 0.33 # Deviation from typical human proportion.
        anomaly_scores.append(self._sigmoid(proportion_anomaly * 8 - 2)) # Higher deviation = more suspicious.

        # --- Jaw line variance ---
        jaw_points = points[0:17] # Jaw line landmarks.
        jaw_dist = np.linalg.norm(np.diff(jaw_points, axis=0), axis=1) # Distances between consecutive jaw points.
        jaw_cv = np.std(jaw_dist) / (np.mean(jaw_dist) + 1e-6) # Coefficient of variation - AI faces often have unnaturally uniform jaw lines.
        # AI faces often have unnaturally smooth or irregular jaw lines.
        anomaly_scores.append(self._sigmoid(abs(jaw_cv - 0.15) * 10 - 1)) # Deviation from typical human jawline variation.

        final_score = float(np.mean(anomaly_scores)) # Average anomaly score across all checks - higher means more likely AI.
        return True, float(np.clip(final_score, 0.0, 1.0))

    
    # --------------------------------------------------------------------------------------
    # Combination + Helpers
    # --------------------------------------------------------------------------------------
    def _combine(self, signals: ImageSignals, face_detected: bool) -> float:
        """
        Weighted average of all signals. Redistributes anatomical weight
        to classifier when no face i detected.
        """
        w = self._WEIGHTS.copy()

        if not face_detected:
            w["classifier"] += w["anatomical"]
            w["anatomical"] = 0.0
        
        scores = {
            "fft": signals.fft_artifact_score,
            "noise": signals.noise_pattern_score,
            "metadata": signals.metadata_score,
            "lbp": signals.lbp_texture_score,
            "classifier": signals.classifier_score,
            "anatomical": signals.anatomical_score or 0.0,
        }

        return float(sum(scores[k] * w[k] for k in w))
    
    def _confidence(self, signals: ImageSignals, face_detected: bool) -> ConfidenceLevel:
        """
        Confidence is about agreement between signals, not the score itself. All signals agreeing
        strongly -> high confidence. Signals disagreeing -> low confidence.
        """
        scores = [
            signals.fft_artifact_score,
            signals.noise_pattern_score,
            signals.metadata_score,
            signals.lbp_texture_score,
            signals.classifier_score,
        ]

        if face_detected and signals.anatomical_score is not None:
            scores.append(signals.anatomical_score)
        
        variance = float(np.var(scores))

        if variance < 0.02:
            return ConfidenceLevel.HIGH
        elif variance < 0.08:
            return ConfidenceLevel.MEDIUM
        else:
            return ConfidenceLevel.LOW
    
    def _verdict(self, probability: float) -> str:
        if probability >= settings.ai_verdict_threshold:
            return "AI generated"
        elif probability >= settings.possible_ai_verdict_threshold:
            return "Possibly AI generated or heavily edited"
        else:
            return "Likely human taken photo"

    def _load_image(self, contents: bytes) -> Image.Image:
        image = Image.open(io.BytesIO(contents))
        # Normalise format - some operations need RGB specifically.
        if image.mode not in ("RGB", "L"):
            image = image.convert("RGB")
        return image
    
    def _extract_exif(self, contents: bytes) -> dict[str, Any]:
        try:
            image = Image.open(io.BytesIO(contents))
            exif = image._getexif()
            return exif or {}
        except Exception:
            return {}
    
    @staticmethod
    # Sigmoid function to map any value to a 0.0-1.0 range in an S-curve shape. Used for normalizing raw signal measurements into a consistent score range.
    def _sigmoid(x: float) -> float:
        """Maps any value to 0.0-1.0 on an S-curve."""
        return 1.0 / (1.0 + math.exp(-x))
